name: soccerTwos
channels:
  - defaults
dependencies:
  - python=3.7
  - cudatoolkit=10.1
  - pytorch::pytorch
  - absl-py
  - pyparsing
  - jupyterlab
  - scikit-image
  - pip:
    - mlagents==0.27.0
    - wandb
    - opencv-python
    - termcolor
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - hydra-core==0.11.3
    - pandas
    - ipdb
    - tqdm
    - torchvision
    - yapf
    - sklearn
    - matplotlib
    - kornia
